[package]
name = "rust_lib"
version = "0.1.0"
authors = ["kir4ik <vlados.linkoln@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.82"

[lib]
crate-type = ["cdylib"]
